version: "3.9"

services:
  webp-converter:
    build: .
    container_name: webp-converter
    ports:
      - "5008:5008"
    environment:
      - PORT=5008
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./:/app

